#!/usr/bin/env node
/**
 * Generate gitignored WeChat DevTools and runtime configuration from
 * apps/miniapp/.env. Public origins are generated rather than committed so the
 * same native shell can target local/staging/production environments.
 *
 * DevTools opens apps/miniapp/miniprogram as the project root. The AppSecret
 * remains server-only.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const miniappRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const programRoot = path.join(miniappRoot, "miniprogram");
const repoRoot = path.resolve(miniappRoot, "../..");
const envPath = path.join(miniappRoot, ".env");
const privateConfigPath = path.join(programRoot, "project.private.config.json");
const runtimeConfigPath = path.join(programRoot, "config.js");

loadEnvFile(envPath);

const appId = requireValue("MINIAPP_APP_ID");
const apiBaseUrl = requireOrigin("MINIAPP_API_BASE_URL");
const webBaseUrl = requireOrigin("MINIAPP_WEB_BASE_URL");

const existing = existsSync(privateConfigPath)
  ? JSON.parse(readFileSync(privateConfigPath, "utf8"))
  : {};
const privateConfig = {
  ...existing,
  appid: appId,
  projectname: "OpenTrip",
  compileType: "miniprogram",
};

writeFileSync(
  privateConfigPath,
  `${JSON.stringify(privateConfig, null, 2)}\n`,
  { mode: 0o600 },
);
writeFileSync(
  runtimeConfigPath,
  [
    "// Generated by scripts/sync-config.mjs. Do not edit or commit.",
    "module.exports = Object.freeze({",
    `  apiBaseUrl: ${JSON.stringify(apiBaseUrl)},`,
    `  webBaseUrl: ${JSON.stringify(webBaseUrl)},`,
    "});",
    "",
  ].join("\n"),
  { mode: 0o600 },
);

console.log(
  `Synced Mini Program configuration into ${path.relative(repoRoot, privateConfigPath)} and ${path.relative(repoRoot, runtimeConfigPath)}`,
);

function loadEnvFile(filePath) {
  if (!existsSync(filePath)) {
    throw new Error(`Missing ${path.relative(repoRoot, filePath)}`);
  }
  for (const rawLine of readFileSync(filePath, "utf8").split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const separator = line.indexOf("=");
    if (separator < 1) continue;
    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (process.env[key] === undefined) process.env[key] = value;
  }
}

function requireValue(name) {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`${name} is required in apps/miniapp/.env`);
  return value;
}

function requireOrigin(name) {
  const value = requireValue(name);
  const url = new URL(value);
  if (url.protocol !== "https:" && url.protocol !== "http:") {
    throw new Error(`${name} must use http or https`);
  }
  if (url.pathname !== "/" || url.search || url.hash) {
    throw new Error(`${name} must be an origin without a path, query, or hash`);
  }
  return url.origin;
}
