export const copy = {
  common: {
    retry: "重试",
    loading: "正在加载…",
    unknownError: "操作失败，请稍后重试",
    apiBaseUrlMissing: "尚未配置 API 地址",
  },
  auth: {
    title: "继续规划旅程",
    subtitle: "使用你的 OpenTrip 账号登录",
    wechat: "微信一键登录",
    wechatConfirm: "确认并登录",
    wechatSubmitting: "正在连接微信…",
    wechatError: "微信登录失败，请重试",
    wechatCodeMissing: "无法获取微信登录凭证，请在微信客户端重试",
    wechatNotConfigured: "微信登录尚未启用（需在服务端配置小程序 AppID/AppSecret）",
    wechatNickname: "微信昵称",
    wechatNicknamePlaceholder: "填写或选择微信昵称",
    wechatNicknameRequired: "请先填写微信昵称",
    wechatNicknameRejected: "昵称未通过微信安全审核，请重新填写",
    wechatAvatarRequired: "请选择微信头像后继续",
    profileUpdateError: "昵称保存失败，请重试",
    avatarUploadError: "头像上传失败，请重试",
    divider: "或使用邮箱登录",
    email: "邮箱",
    emailPlaceholder: "name@example.com",
    password: "密码",
    passwordPlaceholder: "输入密码",
    submit: "登录",
    submitting: "正在登录…",
    invalidInput: "请输入邮箱和密码",
  },
  trips: {
    title: "我的旅程",
    subtitle: "在微信里快速查看和协作规划",
    create: "新建旅程",
    closeCreate: "收起",
    empty: "还没有旅程，创建第一个计划吧",
    loadError: "无法加载旅程",
    titleField: "旅程名称",
    titlePlaceholder: "例如：京都周末",
    destinationField: "目的地（可选）",
    destinationPlaceholder: "例如：京都",
    dayCountField: "天数",
    createSubmit: "创建并打开",
    creating: "正在创建…",
    createInvalid: "请输入旅程名称，并填写 1–60 天",
    members: "位成员",
    stops: "个地点",
    signOut: "退出",
    signingOut: "正在退出…",
  },
  detail: {
    loadError: "无法加载行程详情",
    emptyDay: "当天还没有安排",
    vote: "赞",
    voting: "提交中…",
    dayPrefix: "第",
    daySuffix: "天",
    destinationPending: "地点待定",
  },
} as const;
